<header>
    <!-- https://www.canva.com/ai-logo-generator/ prompt: generate a simple company logo for a music composing software called GROJBAND -->
    <a href="index.html"><img id="Logo" src="images/GrojBand.png" alt="GrojBand Logo"></a>
    <nav>
        <a class="NavButton" href="index.php">Home</a>
        <a class="NavButton" href="about.php">About</a>
        <a class="NavButton" href="login.php">Login</a>
        <a class="NavButton" href="jobs.php">Jobs</a>
        <a class="NavButton" href="apply.php">Apply</a>
    </nav>
</header>